# Nome da aplicacao
spring.application.name=BackendUEG202601

# Configuracoes de conexao com o banco
spring.datasource.url=jdbc:postgresql://localhost:5432/bdueg202601
spring.datasource.username=postgres
spring.datasource.password=100916

# Mostra no console os comandos SQL
spring.jpa.show-sql=true

# Dialeto para o PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Permite que o Hibernate atualize as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update